src/feeddb/explorer/urls.py
# VG: I suggest discussing and coordinating most ideas about 
#     changing the design of URLs in this file. 

from django.conf.urls import patterns, url
from feeddb.explorer.views import * 
from django.conf import settings 

urlpatterns = patterns('',
  url(r'^$', portal_page),
  url(r'^bucket/add/$', bucket_add),
  url(r'^bucket/(?P<id>\d+)/$', bucket_detail),
  url(r'^bucket/(?P<id>\d+)/delete/$', bucket_delete),
  url(r'^bucket/(?P<id>\d+)/download/$', bucket_download),
  url(r'^bucket/(?P<id>\d+)/remove_trials/$', bucket_remove_trials),
  url(r'^trial/search/$', trial_search),
  url(r'^trial/search/put/$', trial_search_put),
  url(r'^trial/(?P<id>\d+)/$', trial_detail, name='trial_detail'),
  url(r'^trial/(?P<id>\d+)/remove/(?P<bucket_id>\d+)/$', trial_remove),
  url(r'^trial/(?P<id>\d+)/put/$', trial_add, name='trial_add'),
  url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.EXPLORER_STATIC_ROOT}),
)

src/feeddb/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings
from django.http import HttpResponseRedirect
from views import *
from feed.views import *

from haystack.query import SearchQuerySet

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^feeddb/', include('feeddb.foo.urls')),

    (r'^static/(?P<path>.*)$',
     'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    (r'^uploads/(?P<path>.*)$',
     'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^admin/', include(admin.site.urls)),
    #(r'^feed/', include(admin.site.urls)),
    (r'^$', 'feeddb.feed.views.welcome'),
    #(r'^$', include('feeddb.feed.urls')),

    (r'^explorer/', include('feeddb.explorer.urls')),

    (r'^about', 'feeddb.feed.views.about'),
    (r'^happybrowser', 'feeddb.feed.views.happybrowser'),
    (r'^welcome', lambda r: HttpResponseRedirect('/')),
    (r'^login$', login_view),
    (r'^logout$', logout_view),
    (r'^search/', FeedSearchView()),
    (r'^profile/', UserOwnProfileChangeView.as_view()),
    url(r'^_clone_from_container/(?P<container_type>\w+)/(?P<container_pk>\d+)',
        ModelCloneView.as_view(), name='clone_from_container'),
    url(r'^_clone_subject_from_study/(?P<container_pk>\d+)',
        ModelCloneView.as_view(), name='clone_subject_from_study',
        kwargs={ 'container_type': 'study', 'clone_subject': True }),
    url(r'^_clone_study', ModelCloneView.as_view(), name='clone_study'),

    url(r'^ajax/add_taxon', TaxonModalAddView.as_view(), name='modal_add_taxon'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

src/feeddb/explorer/models.py
from django.db import models
from feeddb.feed import models as feedmodels

# Create your models here.

class Bucket(feedmodels.FeedBaseModel):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True,null=True)
    trials = models.ManyToManyField(feedmodels.Trial, through='TrialInBucket')

    def default_zipfile_name(self):
        name = self.title.replace(' ', '_').strip().lower()
        return "%s.zip" % name

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "Collection"


class TrialInBucket(models.Model):
    trial = models.ForeignKey(feedmodels.Trial)
    bin = models.ForeignKey(Bucket)

src/feeddb/explorer/views.py
# VG: I suggest this usage for views.py:
#  This is where back end (DB access & data massaging) and
#  front end (presentation on web pages) are connected to each other.
#  We will only keep the connecting code here.
#  All non-trivial computations should be factored out separate modules.

import os, re, tempfile, zipfile, csv
from django.core.servers.basehttp import FileWrapper
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, Template
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, StreamingHttpResponse
from django.contrib.auth import authenticate, login,logout
from django.db.models import Q
from django.utils.html import escape
from feeddb.explorer.models import *
from feeddb.feed.models import *
from feeddb.explorer.forms import *
from django.conf import settings
from django.contrib import messages

import os.path

from unicodecsv import UnicodeWriter


def portal_page(request):
    c = RequestContext(request, {'title': 'FeedDB Explorer', 'content': 'Welcome!'  })
    return render_to_response('explorer/index.html', c, mimetype="text/html")

def bucket_add(request):
    message=None

    if request.method=='POST':
        form = BucketModelForm(request.POST)
        if form.is_valid():
            if request.user.id:
                form.instance.created_by = request.user
            form.save()

            if request.user.id is None:
                anonymous_bucket_ids(request, form.instance.id)

            messages.success(request, "Successfully added the data collection.")
            c = RequestContext(request, {'title': 'FeedDB Explorer',  'form':form})
            return render_to_response('explorer/bucket_detail.html', c)
        else:
            messages.error(request, "Failed to add the data collection.")
    else:
        bucket = Bucket()
        form = BucketModelForm(instance=bucket)

    c = RequestContext(request, {'title': 'FeedDB Explorer',  'form':form})
    return render_to_response('explorer/bucket_add.html', c)

def bucket_delete(request, id):
    bucket = get_bucket(request, id)
    bucket.delete()
    messages.success(request, 'Successfully deleted the data collection:%s' % bucket)
    return HttpResponseRedirect('/admin/feed/')

def get_bucket(request, id):
    from django.http import Http404
    id = int(id)
    try:
        if request.user.id:
            if request.user.is_superuser:
                bucket = Bucket.objects.get(pk=id)
            else:
                bucket = Bucket.objects.get(pk=id, created_by=request.user)
        else:
            # check session for specified bucket id (throws ValueError if not found)
            session_bucket_ids = anonymous_bucket_ids(request)
            session_bucket_ids.index(id)

            # get the bucket, with extra check that it's not owned by somebody else
            bucket = Bucket.objects.get(pk=id, created_by__isnull=True)
    except (Bucket.DoesNotExist, ValueError):
        raise Http404('You do not own a data collection with primary key %s.' % id)

    return bucket

def anonymous_bucket_ids(request, id=None):
    ids = request.session.setdefault('bucket_ids', [])
    if id is not None:
        ids.append(id)
        request.session.modified = True
    return ids

def get_user_buckets(request):
    if request.user.id:
        buckets = Bucket.objects.filter(created_by=request.user)
    else:
        buckets = Bucket.objects.filter(created_by__isnull=True, id__in=anonymous_bucket_ids(request))
    return buckets

# VG-claim: Finishing this view in the 1st pass needs only
#     a detailed implementation of the bucket_detail.html template.
#  However, we'll later need to improve efficiency of DB lookups.
def bucket_detail(request, id):
    message=None
    bucket = get_bucket(request, id)

    if request.method=='POST':
        form = BucketModelForm(request.POST, instance=bucket)
        if form.is_valid():
            form.save()
            messages.success(request, "Saved all changes to data collection.")
            return HttpResponseRedirect(request.path)
        else:
            messages.error(request, "Failed to save changes to data collection.")
    else:
        form = BucketModelForm(instance=bucket)

    trials = bucket.trials.all().select_related(
        'session__experiment__subject__taxon',
        'behaviorowl_primary',
        ).prefetch_related('bucket_set')

    c = RequestContext(request, {
        'title': 'FeedDB Explorer',
        'form': form,
        'trials': trials,
        })
    return render_to_response('explorer/bucket_detail.html', c)

def bucket_download(request, id):
    # TODO: access control
    message=""
    bucket = get_bucket(request, id)

    if request.method=='POST':
        try:
            zipfile_name = request.POST['zipfile_name']
        except KeyError:
            zipfile_name = bucket.default_zipfile_name()
            if zipfile_name == "":
                messages.error(request, 'No zip file name selected.')
                c = RequestContext(request, {'title': 'FeedDB Explorer'})
                return render_to_response('explorer/base.html', c)

        if not zipfile_name.endswith(".zip"):
            zipfile_name +=".zip"

        download_choice= request.POST['download_choice']
        channel_choice = request.POST['channel_choice']
        #meta_option= request.POST['meta_option']
        quotechar_char='"'
        #delimiter= request.POST['delimiter']
        #if delimiter =="tab":
        #    delimiter_char = '\t'
        #elif delimiter =="comma":
        #    delimiter_char = ','
        #else:
        delimiter_char = ','


        #get selected fields
        field_selected = []
        for item in request.POST.items():
            if(item[1]=="on" and item[0].startswith("chk:")):
                field_selected.append(item[0])
                message += item[0]+"\n"
        if  (download_choice=="0" or  download_choice=="2") and  len(field_selected) ==0:
            messages.error(request, 'No fields selected.')
            c = RequestContext(request, {'title': 'FeedDB Explorer'})
            return render_to_response('explorer/base.html', c)
        meta_selected = {}
        for field in field_selected:
            parts=field.split(":")
            if not parts[1] in meta_selected:
                meta_selected[parts[1]]=[]
            parameter=parts[1]+":"+parts[2]
            meta_selected[parts[1]].append([parts[2],request.POST[parameter]])

         #get selected channels
        channel_selected = []
        channel_headers=[]
        for item in request.POST.items():
            if(item[1]=="on" and item[0].startswith("channel:")):
                channel_selected.append(item[0])
                message += item[0]+"\n"
        if  (channel_choice=="1" and len(channel_selected) ==0):
            messages.error(request, 'No channels selected.')
            c = RequestContext(request, {'title': 'FeedDB Explorer'})
            return render_to_response('explorer/base.html', c)
        channel_download = []
        channel_selected.sort()
        trials_download =[]
        for ch in channel_selected:
            parts=ch.split(":")
            channel_download.append([parts[1], parts[2]])
            channel_headers.append("Trial %s:Channel %s" % (parts[1], parts[2]))
            if not parts[1] in trials_download:
                trials_download.append(parts[1])
        filenames={}

        # create a temporary folder to store files
        from time import time
        tempdir = settings.EXPLORER_TEMPORARY_FOLDER+"/"+str(time()).replace('.', '')

        try:
            os.makedirs(tempdir)
        except OSError, err:
            messages.error(request, 'Failed to create folder for storing downloaded files.')
            c = RequestContext(request, {'title': 'FeedDB Explorer'})
            return render_to_response('explorer/base.html', c)

        #
        # create meta data if the user has chosen to do so
        #
        if  (download_choice=="0" or  download_choice=="2"):
            #create trials mate data file and out it into the temp zip file
            full_filename = "%s/trials.csv" % tempdir
            filenames["trials.csv"]=full_filename

            metaWriter = UnicodeWriter(open(full_filename,"w"), delimiter=delimiter_char,  doublequote='false' , escapechar ='\\', quotechar=quotechar_char, quoting=csv.QUOTE_MINIMAL)

            #output trials
            #output headers
            headers=["Trial:ID"]
            for key, value in meta_selected.items():
                if not key in('Setup','EmgSetup','SonoSetup','Sensor','EmgSensor','SonoSensor','Channel','EmgChannel','SonoChannel',
                              'PressureChannel','ForceChannel','StrainChannel','KinematicsChannel','EventChannel'):
                    for v in value:
                        headers.append( v[1] )
            metaWriter.writerow(headers)

            objects={}
            for trial in bucket.trials.all():
                values=[trial.id]
                objects["Session"]= trial.session
                objects["Experiment"]=trial.session.experiment
                objects["Study"]=trial.session.experiment.study
                objects["Subject"]=trial.session.experiment.subject
                objects["Trial"]=trial
                for key, value in meta_selected.items():
                    if key in objects:
                        for v in value:
                            s=getattr(objects[key], v[0])
                            if hasattr(s,'split'):
                                ss=s.split('\r\n')
                                if len(ss)>1:
                                    s=' '.join(ss)

                            values.append(s)

                metaWriter.writerow(values)

            #output channels
            #generate channel headers
            headers=["Channel:ID"]

src/feeddb/explorer/templates/explorer/base.html
{% extends "admin/base_site.html" %}

src/feeddb/explorer/templates/explorer/base_with_sidebar.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>{% block title %}{{ title }}   {% endblock %}</title>
<link rel="stylesheet" href="/explorer/static/css/styles.css" type="text/css" />
</head>
<body>
<div class="wrapper">
   <div class="top">
     <div class="header">
          <!-- TITLE -->
           <h1><a href="#">FeedDB Explorer</a></h1>
           <h2>Exploring Data in FeedDB</h2>
          {%if user.is_authenticated %}	
               <div class="greeting">welcome! {{user}}</div>
          {% endif %}
			<div class="clear"></div>
			<!-- END TITLE -->
		</div>
		<div class="menu">
			{% include "explorer/topmenu.html" %}
		</div>
	</div>		
	<div class="content">	
		<div class="page-content">	
			<!-- CONTENT -->
                                                                                {% block message %}{{ message }}{% endblock %}
			        {% block content %}{{ content }}{% endblock %}
			
			<!-- END CONTENT -->
		</div>
	</div>


<div class="sidebar">	
		
		<!-- SIDEBAR -->
<ul>
{%if user.is_authenticated %}
{% include "explorer/buckets_sidebar.html" %}
{% else %}
{% include "explorer/login_sidebar.html" %}
{%endif %}
		</ul>
		<!-- SIDEBAR -->

	</div>

	<div class="clear"></div>			

	<p class="footer"><a href="http://nescent.org">NESCent</a> 2009</p>
</div>

			

<div style="text-align: center; font-size: 0.75em;"></div></body>
</html>

src/feeddb/explorer/templates/explorer/bucket_add.html
{% extends "explorer/base.html" %}
{% load explorer_display %}
{% block extra_js %}
<script type="text/javascript" src="/explorer/static/js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="/explorer/static/js/jquery.checkboxes.js"></script>
{% endblock %}

{% block pretitle %}
  <div class="masthead">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h1>Add New Data Collection</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <hr />
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="col-xs-8">
    <form action="{% url "explorer.views.bucket_add" %}" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col-xs-3">
          <label for="id_title">Title:</label>
        </div>
        <div class="col-xs-9">
          {{ form.title }}
        </div>
      </div>
      <div class="row">
        <div class="col-xs-3">
          <label for="id_description">Description:</label>
        </div>
        <div class="col-xs-9 short-box">
          {{ form.description }}
        </div>
      </div>
      <div class="row">
        <div class="col-xs-3 col-xs-offset-3">
          <input class="btn btn-primary full-width" type="submit" value="Add" />
        </div>
      </div>
    </form>
  </div>
{% endblock %}

src/feeddb/explorer/templates/explorer/bucket_detail.html
{% extends "admin/base_site.html" %}
{% load explorer_display %}
{% block bodyclass %}collection-detail{% endblock %}
{% block extra_js %}
<script type="text/javascript" src="/explorer/static/js/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="/explorer/static/js/jquery.checkboxes.js"></script>
{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block pretitle %}
  <div class="masthead">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h1>Download Trials</h1>
          <h2>My Data Collection Details</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <hr />
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="col-xs-12">
  <form action="{% url "explorer.views.bucket_detail" form.instance.id %}" method="POST">
  {% csrf_token %}
  <div class="row">
    <div class="col-xs-8">
      <div class="row">
        <div class="col-xs-3">
          <label for="id_title">Title:</label>
        </div>
        <div class="col-xs-9">
          {{ form.title }}
        </div>
      </div>
      <div class="row">
        <div class="col-xs-3">
          <label for="id_description">Description:</label>
        </div>
        <div class="col-xs-9 short-box">
          {{ form.description }}
        </div>
      </div>
    </div>
    <div class="col-xs-3 col-xs-offset-1">
      <button class="btn btn-default full-width top-element" type="submit">Save</button>
      <a class="btn btn-primary" href="{% url "explorer.views.bucket_download" form.instance.id %}" class="downloadlink">Download</a></li>
    </div>
    </div>
  </form>
</div>
</div>
<script language="javascript">
function checkbox_clicked(obj){
   if(obj.checked){
	$("#trial_form").checkCheckboxes();	
   }else{
           	$("#trial_form").unCheckCheckboxes();
   }
}

</script>
<div class="row">
  <div class="col-xs-12">
    <h3>Trials</h3>
    <form action = "{% url "explorer.views.bucket_remove_trials" form.instance.id %}" method="POST" id="trial_form" name ="trial_form">
      {% csrf_token %}
      <table class="table table-striped table-bordered">
        <tr>
          <th style="width:28px;"><input type="checkbox" id="select_all" onclick ="checkbox_clicked(this)" /></th>
          <th>Name</th>
          <th>Species</th>
          <th>Primary Behavior</th>
          <th>Food Type</th>
        </tr>
        {% for trial in trials %}
        <tr class="{% cycle 'row1'  'row2' %}">
          <td><input type="checkbox" name="{{trial.id}}" id="{{trial.id}}" class="check_trial" /></td>
          <td><a href="{% url "explorer.views.trial_detail" trial.id %}">{{trial.title}}</a></td>
          <td>{{trial.session.experiment.subject.taxon.genus}} {{trial.session.experiment.subject.taxon.species}}</td>
          <td>{{trial.behaviorowl_primary}}</td>
          <td>{{trial.food_type}}</td>
        </tr>
        {% endfor %}
      </table>
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <input class="btn btn-primary bottom-element" type="submit" value="Remove Selected Records" />
        </div>
      </div>
    </form>
  </div>
  </div>

{% endblock %}

src/feeddb/explorer/templates/explorer/bucket_download.html
{% extends "admin/base_site.html" %}
{% load explorer_display %}
{% block bodyclass %}collection-detail{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block pretitle %}
<div class="masthead">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h1>Download Trials</h1>
        <h2>My Data Collection Metadata: {{bucket}}</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <hr />
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="col-xs-12">
<form action="{% url "explorer.views.bucket_download" bucket.id %}" id="meta_form" name ="meta_form" method="POST">
{% csrf_token %}

<div class="row">
      <div class="col-xs-2">
        <label for="id_title">Zip File Name:</label>
      </div>
      <div class="col-xs-3">
        <span class="file-name">{{file_name}}</span>
      </div>
      <div class="col-xs-3">
        <label for="id_description">Choose Data to Download:</label>
      </div>
      <div class="col-xs-4 radios download">
        <div class="row">
          <div class="col-xs-1">
            <input for="id_description" type="radio" name="download_choice" value="0" onclick="document.getElementById('meta_div').style.display='block';document.getElementById('channels_div').style.display='none';"/>
          </div>
          <div class="col-xs-11">
            <label>Meta data only</label>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-1">
            <input for="id_description" type="radio" name="download_choice"  value="1" onclick="document.getElementById('meta_div').style.display='none';document.getElementById('channels_div').style.display='block';" />
          </div>
          <div class="col-xs-11">
            <label>Data only</label>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-1">
            <input for="id_description" type="radio" name="download_choice"  value="2" checked="checked" onclick="document.getElementById('meta_div').style.display='block'; document.getElementById('channels_div').style.display='block';"/>
          </div>
          <div class="col-xs-11">
            <label>Both meta data and data</label>
          </div>
        </div>
      </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div id="meta_div">
      <!-- h3>CSV format</h3>
      <table><tr><td class="TdField">Delimiter</td><td class="TdValue"><select name="delimiter"><option value="tab">tab</option><option value="comma">comma</option></select></td></tr>
      <tr><td class="TdField">Quote Char</td><td class="TdValue"><input name="quotechar" value='"' />(1 character)</td></tr>
      </table -->
      
      <!-- h3>Metadata Option</h3>
      <table><tr><td><input type="radio" name="meta_option"   value="0"  checked="checked" />  store channel meta data in separate files</td></tr>
      <tr><td><input type="radio"  name="meta_option"  value="1"  />  store channel meta data with trial meta data</td></tr>
      </table -->
      
      <h3>Select Trial Metadata Fields</h3>
      <table class="table table-striped table-bordered">
        <tr>
          <th>Source</th>
          <th>Field</th>
          <th>Column Header</th>
          <th>
          <input type="checkbox" class="checkall" value="blank" checked="checked" /></th></tr>
          
          {% for form in meta_forms %}
          
          {%for field in form %}
          {%if forloop.first %}<tr class=" {% cycle 'even'  'odd' %}"><td rowspan="{{form.fields|length}}">{{form.Meta.name}}</td>{%else%}<tr class="{% cycle 'even'  'odd' %}">{%endif%}
          <td>{{form.Meta.name}}: {{field.name}}</td><td><input size="20" name="{{form.Meta.name}}:{{field.name}}" value="{{form.Meta.name}}:{{field.label}}" /></td>
          <td class="choose"><input type="checkbox" name="chk:{{form.Meta.name}}:{{field.name}}" checked="checked" /></td>
        </tr>
          {% endfor %}
          {% endfor %}
      </table>  
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div id="channels_div">
      <h3>Channel Selection</h3>
      <table class="table table-striped table-bordered">
        <tr><td  class="TdValue"><input type="radio"  name="channel_choice"  value ="0" onclick="document.getElementById('channels_sel_div').style.display='none';" checked="checked"/> <label> All channels: all trial files in current bucket will be downloaded as original files.</label> </td></tr>
        <tr><td  class="TdValue"><input type="radio"   name="channel_choice"  value ="1" onclick="document.getElementById('channels_sel_div').style.display='block';" /> <label> Selected channels: selected channels will be merged side by side into one file for downloading.</label> </td></tr>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div id="channels_sel_div" style="display:none;">
      <h3>Select Channels</h3>
      <p>All channels from all trials in the current bucket will be displayed below and user can select individual channels for each trial for downloading. </p>
      <table class="table table-striped table-bordered">
        <tr>
        <th rowspan="2">Trial</th>
        <th colspan="6">Channels</th>
        <th rowspan="2">Select All <br/><input type="checkbox" class="checkall" checked="checked"/></th>
        </tr>
        <tr>				  
        <th>Order</th>
        <th>Name</th>
        <th>Technique</th>
        <th>Rate</th>
        <th>Location</th>
        <th>Side</th>
        </tr>
          {% for trial in bucket.trials.all %} 
          {% for lineup in trial.session.channellineup_set.all %}
          {%if forloop.first %}<tr class="{% cycle 'even'  'odd' %}"><td rowspan="{{trial.session.channellineup_set.all|length}}">{{trial.title}}</td>{%else%}<tr class="{% cycle 'even'  'odd' %}">{%endif%}
          
          <td>{{lineup.position}}</td>
          {%if lineup.channel %}
          <td>{{lineup.channel.name}}</td>
          <td>{%technique_label lineup.channel.setup.technique%}</td>
          <td>{{lineup.channel.rate}}</td>
          <td>{% display_lineup_location lineup %}</td> 
          <td>{% display_lineup_side lineup %}</td> 
          {%else%}
          <td>*dead*</td>
          <td>*dead*</td>
          <td>*dead*</td>
          <td>*dead*</td>
          <td>*dead*</td>
          {%endif%}
          <td><input name="channel:{{trial.id}}:{{lineup.position}}" type="checkbox" checked="checked" /></td>  
        </tr>
          {%endfor %}
          {%endfor %}
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-3 col-xs-offset-9">
    <input class="btn btn-primary" type="submit" value="Download Records" />
  </div>
</div>
</form>
</div>
{% endblock %}

{% block extra_js %}
<script>

jQuery(document).on('ready', function() {

  $('.checkall').on('change', function() {
    $(this).parents("table").find(":checkbox").prop('checked', this.checked);
  });
  
  
  
});
</script>
{% endblock extra_js %}

src/feeddb/explorer/templates/explorer/bucket_list.html
{% extends "explorer/base.html" %}

{% block breadcrumbs %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="breadcrumbs">
        <ul id="crumbs">
          <li><a href="/">Home</a></li>
          <span>/</span>
          <li>My Data Collections</li>
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
  <div class="col-xs-12">
    <h3>My Data Collections</h3>
    <ul class="object-tools">
      <li><a href="{% url "explorer.views.bucket_add" %}" class="addlink"><span class="glyphicon glyphicon-plus-sign"></span>Add Collection</a></li>
    </ul>
    <table class="table table-bordered table-striped">
    	<thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Number of Trials</th>
          <th>Description</th>
          <th>Action</th>
        </tr>
      </thead>
      {% for b in buckets %}
      <tr  class="{% cycle 'row1' 'row2' %}">
        <td><a  href="{% url "explorer.views.bucket_detail" b.id %}">{{b.id}}</a></td>
        <td><a  href="{% url "explorer.views.bucket_detail" b.id %}">{{b.title}}</a></td>
        <td>{{b.trials.all|length}}</td>
        <td>{%if b.description%} {{b.description}}{%endif%}</td>
        <td><a href="javascript: if(confirm('Do you really want to delete this bucket:{{b}}?')==true)window.location.href='{% url "explorer.views.bucket_delete" b.id %}';">Delete</a>&nbsp;&nbsp;
        <a href="{% url "explorer.views.bucket_download" b.id %}">Download</a></td>
      </tr>
    {% endfor %}
    </table>
  </div>
{% endblock %}

src/feeddb/explorer/templates/explorer/buckets_sidebar.html
<li>
<h4>Your Buckets</h4>
<ul>
{% if buckets %}
{% for b in buckets %}
 <li><a  href="/explorer/bucket/{{ b.id}}">{{b.id}}. {{b.name}}</a></li>
{% endfor %}
 <li><a  href="/explorer/bucket/add">add new bucket</a></li>


{% endif %}
</ul>
</li>

src/feeddb/explorer/templates/explorer/error.html
{% extends "explorer/base.html" %}

src/feeddb/explorer/templates/explorer/search_trial.html
{% extends "explorer/base.html" %}
{% block content %}
{% include "explorer/include/search_trial_form.html" %}
{% endblock %}