src/feeddb/feed/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',

)

src/feeddb/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings
from django.http import HttpResponseRedirect
from views import *
from feed.views import *

from haystack.query import SearchQuerySet

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^feeddb/', include('feeddb.foo.urls')),

    (r'^static/(?P<path>.*)$',
     'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    (r'^uploads/(?P<path>.*)$',
     'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^admin/', include(admin.site.urls)),
    #(r'^feed/', include(admin.site.urls)),
    (r'^$', 'feeddb.feed.views.welcome'),
    #(r'^$', include('feeddb.feed.urls')),

    (r'^explorer/', include('feeddb.explorer.urls')),

    (r'^about', 'feeddb.feed.views.about'),
    (r'^happybrowser', 'feeddb.feed.views.happybrowser'),
    (r'^welcome', lambda r: HttpResponseRedirect('/')),
    (r'^login$', login_view),
    (r'^logout$', logout_view),
    (r'^search/', FeedSearchView()),
    (r'^profile/', UserOwnProfileChangeView.as_view()),
    url(r'^_clone_from_container/(?P<container_type>\w+)/(?P<container_pk>\d+)',
        ModelCloneView.as_view(), name='clone_from_container'),
    url(r'^_clone_subject_from_study/(?P<container_pk>\d+)',
        ModelCloneView.as_view(), name='clone_subject_from_study',
        kwargs={ 'container_type': 'study', 'clone_subject': True }),
    url(r'^_clone_study', ModelCloneView.as_view(), name='clone_study'),

    url(r'^ajax/add_taxon', TaxonModalAddView.as_view(), name='modal_add_taxon'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

src/feeddb/explorer/models.py
from django.db import models
from feeddb.feed import models as feedmodels

# Create your models here.

class Bucket(feedmodels.FeedBaseModel):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True,null=True)
    trials = models.ManyToManyField(feedmodels.Trial, through='TrialInBucket')

    def default_zipfile_name(self):
        name = self.title.replace(' ', '_').strip().lower()
        return "%s.zip" % name

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = "Collection"


class TrialInBucket(models.Model):
    trial = models.ForeignKey(feedmodels.Trial)
    bin = models.ForeignKey(Bucket)

src/feeddb/feed/views.py
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template.response import SimpleTemplateResponse
from django.db.models.loading import get_model
from django.utils.http import urlencode
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.conf import settings
from models import Study, Experiment, Session, Trial, Taxon, FeedUserProfile

from django.contrib import messages

from haystack.views import FacetedSearchView
from haystack.query import SearchQuerySet
from forms import FeedSearchForm, ModelCloneForm

from feeddb.explorer.models import Bucket
from feeddb.feed.forms import UserOwnProfileForm
from django.views.generic.edit import FormView, CreateView, UpdateView

import logging
logger = logging.getLogger(__name__)

FACET_SORT_ORDER = getattr(settings, 'FACET_SORT_ORDER', [])

def index(request):
    return render(request, "admin/home.html",{'user':request.user})

def about(request):
    return render(request, "about.html",{'user':request.user})

def welcome(request):
    return render(request, "welcome.html",{'user':request.user})

def happybrowser(request):
    return render(request, "happybrowser.html")

def filter_key(f):
    """ See facet_key() in facets.py """
    try:
        index = FACET_SORT_ORDER.index(f[0])
    except ValueError:
        index = 0

    return (index, f[0], f[1])

class UserOwnProfileChangeView(UpdateView):
    form_class = UserOwnProfileForm
    model = FeedUserProfile
    success_url = '/admin/feed'

    def get_object(self):
        # Get the user's profile, or make a new one.
        if self.request.user.is_anonymous():
            raise PermissionDenied("Not logged in")

        try:
            return self.request.user.feeduserprofile
        except ObjectDoesNotExist:
            return self.model(user=self.request.user)

    def form_valid(self, form):
        messages.info(self.request, 'Profile updated successfully')
        return super(UserOwnProfileChangeView, self).form_valid(form)

class TaxonModalAddView(CreateView):
    model = Taxon
    template_name_suffix = '_modal_create_form'
    fields = ['genus', 'species', 'common_name']

    def form_valid(self, form):
        form.save()
        context = {
            'object': form.instance,
            'model': self.model,
            'opts': self.model._meta,
        }
        template_name = 'feed/' + self.model.__name__.lower() + self.template_name_suffix + '_success.html'
        return SimpleTemplateResponse(template_name, context)

class ModelCloneView(FormView):
    """
    This view provides a POST endpoint for the ModelCloneForm, which is only
    accessible on model add pages via a modal form.

    The form should always succeed; it redirects to the new object.
    """

    form_class = ModelCloneForm
    template_name = 'clone_form.html'
    http_method_names = ['post']

    def dispatch(self, request, container_type=None, container_pk=None, clone_subject=False, *args, **kwargs):
        self.container_type = container_type
        self.container_pk = container_pk
        self.clone_subject = clone_subject
        return super(ModelCloneView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(ModelCloneView, self).get_form_kwargs()
        if self.container_type and self.container_pk:
            pk = long(self.container_pk)
            kwargs['container'] = get_model('feed', self.container_type).objects.get(pk=pk)
        elif self.container_type == None:
            kwargs['container'] = None
        kwargs['clone_subject'] = self.clone_subject
        kwargs['prefix'] = 'clone'
        return kwargs

    def _make_message(self, source, recurse):
        if type(source) == Study:
            if recurse:
                return 'New study created. Please edit the study and all its experiments, sessions, and trials.'
            else:
                return 'New study created. Please edit the study.'
        elif type(source) == Experiment:
            if recurse:
                return 'New experiment created. Please edit the experiment and all its sessions and trials.'
            else:
                return 'New experiment created. Please edit the experiment.'
        elif type(source) == Session:
            if recurse:
                return 'New session created. Please edit the session and all its trials.'
            else:
                return 'New session created. Please edit the session.'
        elif type(source) == Trial:
            return 'New trial created. Please edit the trial.'

    def form_valid(self, form):
        from cloning import clone_supported_object
        source = form.cleaned_data['source']
        recurse = form.cleaned_data['recurse']
        if self.request.user.has_perm('feed.add_%s' % type(source).__name__.lower()):
            clone_supported_object(source, recurse=recurse, created_by=self.request.user)
            self.dest = source
        else:
            raise PermissionDenied("Insufficient permission to clone object")

        messages.info(self.request, self._make_message(source, recurse))

        return super(ModelCloneView, self).form_valid(form)

    def get_success_url(self):
        "Redirect to newly created object's edit form when successful"
        return self.dest.get_absolute_url(change=True) + '?is_clone'

def clone_view(request, container_type, container_pk):
    container = get_model('feed', container_type).objects.get(pk=container_pk)

    if request.method == 'POST':
        form = ModelCloneForm(container, request.POST)
    else:
        form = ModelCloneForm(container)

class FeedSearchView(FacetedSearchView):
    def __init__(self):
        super(FeedSearchView, self).__init__(form_class=FeedSearchForm)

    def __call__(self, request):
        self.request = request

        self.form = self.build_form()

        # If we were POSTed to, guess the appropriate form. If it's the trial
        # bucket form, use that gross view function. If it's the search form,
        # we canonicalize the query and redirect to a GET request.
        if request.method == 'POST':
            if request.POST.get('put_bucket', None):
                from feeddb.explorer.views import trial_search_put
                response = trial_search_put(request)
                if isinstance(response, HttpResponseRedirect):
                    return response

                # If we're not using that response, reset the message queue
                # that was emptied when rendering that response.
                #
                # FIXME: rewrite the trial_search_put view as a Form class
                storage = messages.get_messages(request)
                storage.used = False

            q = request.POST.get('q', '')
            old_q = request.POST.get('old_q', '')
            if q == old_q:
                # get facet filters in sorted order
                filters = self.form.searcher._clean_filters(request.POST)
                filters = sorted(filters, key=filter_key)
            else:
                # if user changed search text, reset all filters
                filters = []

            # Add keywords and per_page arguments
            per_page = request.POST.get('per_page', '')
            if per_page:
                filters.insert(0, ('per_page', per_page) )
            if q:
                filters.insert(0, ('q', q) )

            # Get our own URL, add filters to query string, and redirect.
            url = reverse(self)
            if len(filters):
                url += '?' + urlencode(filters)

            return redirect(url)

        self.query = self.get_query()
        self.results = self.get_results()
        return self.create_response()

    def _filter_facet_items(self, items, result_count=0):
        for item in items.items[:]:
            if item.is_selected:
                continue

            # Remove items which would return no results and items which do not
            # further restrict the query (i.e. would return the same number of
            # results when combined with the current query)
            if item.count == 0 or int(item.count) == int(result_count):
                items.items.remove(item)

    def build_page(self):
        try:
            self.results_per_page = int(self.form.cleaned_data['per_page'])
        except (AttributeError, KeyError): # cleaned_data doesn't exist
            pass

        (paginator, page) = super(FeedSearchView, self).build_page()

        if page.has_next():
            page.next_page_params = self.pager_params(page.next_page_number())
        if page.has_previous():
            page.previous_page_params = self.pager_params(page.previous_page_number())

        paginator.first_page_params = self.pager_params(1)

        return (paginator, page)

    def pager_params(self, page_no):
        params = self.request.GET.copy()

        # Remove page parameter for first page
        if page_no == 1 and params.get('page', False):
            params.pop('page')
        else:
            params['page'] = page_no

        return params.urlencode()

    def extra_context(self):
        extra = super(FeedSearchView, self).extra_context()
        # trim down the facet_items: remove facets that don't supply extra constrictions
        facet_list = self.form.searcher.facets
        for facet in facet_list.facets:
            self._filter_facet_items(facet, result_count=len(self.results))

        extra['facet_items'] = facet_list
        from feeddb.explorer.views import get_user_buckets
        extra['available_buckets'] = get_user_buckets(self.request)
        return extra

src/feeddb/feed/templates/search/search.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% block bodyclass %}search{% endblock %}
{% load faceted_search_extras %}

{% block breadcrumbs %}
{% endblock %}

{% block pretitle %}
  <div class="masthead">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h1>Search FEED</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
          <p>Enter a search term to find physiologic data and associated metadata.  A search returns a list of Trials. To refine a search, you can filter by species, anatomical location, sensor type, and/or food type using Filter Results. The columns to the right of the Trial Name provide metadata to aid in selecting Trials. To access data contained within the XMA portal, please <a href="http://xmaportal.org" target="_blank">click here</a>.</p>
	      </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block content %}
<form method="post" action=".">
  <div class="container">
    {% csrf_token %}
    <div class="row">
      <table class="search-box table col-xs-12">
        {# keep track of old query string so we can reset filters if user changes it #}
        <input type="hidden" name="old_q" value="{% if form.q.value %}{{ form.q.value }}{% endif %}">
        <tbody>
          <tr>
            <th class="col-xs-offset-1 col-xs-3 col-lg-offset-1 col-lg-2">
              <label for="id_q">Enter Your Search Term(s):</label>
            </th>
            <td class="col-xs-6">
              {{ form.q }}
            </td>
            <td class="col-xs-2">
              <input type="submit" value="Submit">
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  <div class="row">
    <div class="col-xs-12">
      <hr />
    </div>
  </div>

  {% if page or query %}

  <div class="row">
    <div class="col-xs-3">
      <aside>
        <h3>Filter Results</h3>
        <p>Fields are optional. Multiple terms may be selected for sensor type and anatomical location.</p>
        {% show_facets facet_items 'taxon' %}
        {% show_facets facet_items 'behaviorowl_primary_ancestors' %}
        {% show_facets facet_items 'techniques' %}
        {% show_facets facet_items 'analoc' %}
        {% show_facets facet_items 'food_type' %}
      </aside>
    </div>
    <div class="col-xs-9">
      <div class="row">
        <div class="records-number col-xs-5 col-lg-4">
          <h3>Results ({{ page.paginator.count }})</h3>
          <p>Ordered by Species</p>
        </div>
        <div class="records-list col-xs-7 col-lg-6 col-lg-offset-2">
          <p>Records to display:</p>
          {{ form.per_page }}
        </div>
      </div>
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <th class="choose"><input type="checkbox" id="bucket_checkall" name="checkall" value="blank" /></th>
          <th class="column2">Trial Name<a class="glyphicon glyphicon-info-sign" href="#" data-toggle="tooltip" data-placement="top" title="A single recording of physiologic data for a feeding behavior"></a></th>
          <th class="column3">Trial Date<a class="glyphicon glyphicon-info-sign" href="#" data-toggle="tooltip" data-placement="top" title="The Trial recording start date"></a></th>
          <th class="column4">Species<a class="glyphicon glyphicon-info-sign" href="#" data-toggle="tooltip" data-placement="top" title="Genus and species (Latin name) of the subject recorded during the Trial"></a></th>
          <th class="column5" style="width:90px;">Primary<br />Behavior<a class="glyphicon glyphicon-info-sign" href="#" data-toggle="tooltip" data-placement="top" title="The major feeding behavior recorded during the Trial"></a></th>
          <th class="column6">Sensor Type<a class="glyphicon glyphicon-info-sign" href="#" data-toggle="tooltip" data-placement="top" title="The types of sensors (e.g., strain, EMG) used to record the physiologic signals"></a></th>
          <th class="column7">Anatomical<br />Location<a class="glyphicon glyphicon-info-sign" href="#" data-toggle="tooltip" data-placement="top" title="The anatomical locations of the sensors"></a></th>
          <th class="column8" style="width:102px;">Food Type<a class="glyphicon glyphicon-info-sign" href="#" data-toggle="tooltip" data-placement="top" title="The type of food item processed during the Trial"></a></th>
          <th class="column9" style="width:105px;">My Data Collections<a class="glyphicon glyphicon-info-sign" href="#" data-toggle="tooltip" data-placement="top" title="A list of the datasets compiled by users that contain downloadable physiologic data and/or metadata from this Trial"></a></th>
        </tr>
        </thead>
        {% for result in page.object_list %}
          <tr>
            <td class="choose"><input type="checkbox" name="{{ result.object.id }}" value="on" /></td>
            <td class="column2"><a href="{% url 'trial_detail' result.object.id %}">{{ result.object.title }}</a></td>
            <td class="column3">{{ result.object.start | date:"M j, Y" | default:"unknown" }}</td>
            <td class="column4">{{ result.taxon }}</td>
            <td class="column5">{{ result.behaviorowl_primary }}</td>
            <td class="column6">
              {% for label in result.techniques %}
                {{ label }}{% if not forloop.last %}, {% endif %}
              {% endfor %}
            </td>
            <td class="column7">
              {% for label in result.analoc_direct %}
                {{ label }}{% if not forloop.last %}, {% endif %}
              {% endfor %}
            </td>
            <td class="column8">{{ result.object.food_type }}</td>
            <td class="column9">
              {% for bucket in result.object.bucket_set.all %}
                {# we filter by user in the template so we can use the prefetched results #}
                {% ifequal bucket.created_by user %}
                  <a href="{% url 'explorer.views.bucket_detail' bucket.id %}">{{ bucket }}</a>{% if not forloop.last %}, {% endif %}
                {% endifequal %}
              {% endfor %}
            </td>
          </tr>
        {% empty %}
          <p>No results found.</p>
        {% endfor %}
      </table>
      <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
          <div class="records-selection">
            <p>Add selected records to my data collection:</p>
            <select class="chosen-select" name="bucket">
              <option value=""> - Select - </option>
              <option value="add new bucket" data-toggle="modal" data-target="#new_bucket_div">Add new collection</option>
              {% for bucket in available_buckets %}
                <option value="{{bucket.id}}">{{bucket}}</option>
              {% endfor %}
            </select>
            <input type="submit" name="put_bucket" value="Add" class="btn btn-primary" />
          </div>
        </div>
      </div>

    {% if page.has_previous or page.has_next %}
      <div class="row">
        <div class="records-pagination">
        {% if page.has_previous %}<a href="?{{ page.previous_page_params }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
        |
        {% if page.has_next %}<a href="?{{ page.next_page_params }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
        </div>
        <ul>
          {% comment %}
          How to list page links, kind of.
          {% for page_number in paginator.page_range %}
            <li><a href="?{{ paginator.first_page_params }}&amp;page={{page_number }}">{{ page_number }}</a></li>
          {% endfor %}
          {% endcomment %}
        </ul>
      </div>
    {% endif %}
    </div>
    {% else %}
      {# Show some example queries to run, maybe query syntax, something else? #}
    {% endif %}

    {% block modal %}
    <div class="modal fade" id="new_bucket_div" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h3 class="modal-title">Add New Data Collection</h3>
          </div>
          <div class="modal-body">
              <div class="row">
                <div class="col-xs-3 col-xs-offset-1">
                  <label>Name:</label>
                </div>
                <div class="col-xs-5">
                  <input name="new_bucket_name" size="20" placeholder="Enter new collection name" />
                </div>
              </div>
          </div>
          <div class="modal-footer">
            <div class="row">
              <div class="col-xs-4 col-xs-offset-2">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
              </div>
              <div class="col-xs-4">
                <input type="submit" name="put_bucket" value="Add" class="btn btn-primary" />
              </div>
            </div>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    {% endblock %}
  </form>
</div>
{% endblock content %}

{% block extra_js %}
<script>
// TODO: add spinner graphiczzz!!
jQuery(document).on('ready', function() {
  // Submit the form whenever a change is made to the form
  $('form').find('.facet-group select, #id_per_page :input').on('change', function() {
    this.form.submit();
  });

  $('select[name=bucket]').on('change', function() {
    var show_bucket_name_field = (this.value == 'add new bucket');
    $('#new_bucket_div').toggle(show_bucket_name_field);
  }).change();

  $('#bucket_checkall').on('change', function() {
    $('.choose :checkbox').prop('checked', this.checked);
  });
});

</script>
{% endblock extra_js %}